package controller;

public class BookData {

    public static final String[] name = {
            "The Penguin Book",
            "The Decifestes",
            "Complete Short Stories",
            "Complete Stories",
            "The Story of the Saisian",
            "Penguin Book of the Artist",
            "The Book of Gunk",
            "The Prince of Sherlock Sagas",
            "Last Bather",
            "The Search of a Charles",
            "The Story of a View",
            "Man of the Canday",
            "Day of the Birds",
            "The History of the Father Sammen",
            "A Canterbury Tales",
            "The Book of Missire Lady",
            "Monkey",
            "The Diary of a House",
            "Grapes of the Land",
            "Collected Poems",
            "The Gidge of St Agnes",
            "Poems and Literature",
            "The Ping Men",
            "The Complete Short Stories",
            "The World of My Abusel Hame",
            "The Autobiography",
            "All of Nature",
            "Confessions",
            "The Complete Poems",
            "In Search of Lost Time",
            "Don Quixote",
            "Ulysses",
            "The Great Gatsby",
            "Moby Dick",
            "Hamlet",
            "War and Peace",
            "The Odyssey",
            "One Hundred Years of Solitude",
            "The Divine Comedy",
            "The Brothers Karamazov",
            "Madame Bovary",
            "The Adventures of Huckleberry Finn",
            "The Iliad",
            "Lolita",
            "Crime and Punishment",
            "Alice's Adventures in Wonderland",
            "Wuthering Heights",
            "Pride and Prejudice",
            "The Catcher in the Rye",
            "The Sound and the Fury",
            "To the Lighthouse",
            "Heart of Darkness",
            "Nineteen Eighty Four",
            "Great Expectations",
            "Middlemarch",
            "Gulliver's Travels",
            "Catch-22",
            "One Thousand and One Nights",
            "The Grapes of Wrath",
            "Absalom, Absalom!",
            "Jane Eyre"
    };

    public static final String[] lastName = {
            "Murphy",
            "Diaz",
            "Matthews",
            "Lin",
            "Watts",
            "Hernandez",
            "Bernard",
            "Parks",
            "Wilkerson",
            "Harris",
            "Benitez",
            "Payne",
            "Bradley",
            "Atkinson",
            "Lambert",
            "Schwartz",
            "Gibson",
            "Bray",
            "Roman",
            "Wyatt",
            "Larson",
            "Gutierrez",
            "Hansen",
            "Calhoun",
            "Palmer",
            "Jackson",
            "Weber",
            "Russell",
            "Clements",
            "Ewing"
    };

    public static final String[] firstName = {
            "Willow",
            "Jannet",
            "Joanie",
            "Aimee",
            "Annita",
            "Kandi",
            "Vannesa",
            "Letty",
            "Jeffry",
            "Lewis",
            "Selena",
            "Modesto",
            "Alycia",
            "Deana",
            "Leanne",
            "Nakisha",
            "Emmanuel",
            "Shirly",
            "Merna",
            "Beata",
            "Mao",
            "Helen",
            "Dusty",
            "Hobert",
            "Xavier",
            "Dyan",
            "Ara",
            "Stephane",
            "Vesta",
            "Gus"
    };

    public static final String[] middleName = {
            "Romeo",
            "Ron",
            "Quinton",
            "Pieter",
            "Kylie",
            "Rooney",
            "Roosevelt",
            "Richard",
            "Holden",
            "Rosco",
            "Judon",
            "Ross",
            "Nikolas",
            "Ingmar",
            "Orville",
            "Rourke",
            "Rouvin",
            "Rowan",
            "Lyell",
            "Francesco",
            "Rowney",
            "Roy",
            "Murdock",
            "Royall",
            "Royce",
            "Rriocard",
            "Jourdain",
            "Godart",
            "Patton",
            "Ruby"
    };

    public static final String[] publishing = {
            "Penguin Random House",
            "Hachette Livre (UK)",
            "HarperCollins",
            "Pan Macmillan",
            "Pearson Education",
            "Oxford University Press",
            "Bloomsbury",
            "Simon & Schuster",
            "Faber Independent Alliance",
            "John Wiley & Sons"
    };
}
